### ISSUE TITLE
Cannot build : bash: ./configure: No such file or directory

### ISSUE THREAD

**Issue by sebma** [svnpenn/mp4v2#183]
Hi,

Here's what I get : 
```
$ git clone https://github.com/svnpenn/mp4v2
Cloning into 'mp4v2'...
remote: Counting objects: 4592, done.
remote: Compressing objects: 100% (953/953), done.
remote: Total 4592 (delta 3451), reused 4533 (delta 3422), pack-reused 0
Receiving objects: 100% (4592/4592), 1.74 MiB | 858.00 KiB/s, done.
Resolving deltas: 100% (3451/3451), done.
Checking connectivity... done.
$ cd mp4v2
$ ./configure
bash: ./configure: No such file or directory
```

Can you help me ?

**Comment by svnpenn** [comment]
That is expected, you need to create `configure` before you can use it:

    autoreconf --install --verbose

http://github.com/svnpenn/a/blob/175016d/pkg/mingw64-i686-mp4v2/mingw64-i686-mp4v2.sh#L5

**Comment by sebma** [comment]
@svnpenn Thank you.

N.B. : Please note that the doc directory does not contain any "ReleaseNotes.txt", "BuildSource.txt", "BuildRepository.txt" file.
Therefore, can you please update your README file and add the `autoreconf` command line for others to be able to buid ?

**Comment by sebma** [comment]
Great doc, thanks :)
